name: Build and Push Moodle Docker Image

# Trigger: Run if push 'main'
on:
  push:
    branches: [ main ]
  # workflow_dispatch: # Remove cmt if run from tab Actions (nonautomation)

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Run in Linux githup

    steps:
    # Step 1: Pull code from vm
    - name: Check out code
      uses: actions/checkout@v4

    # Step 2: Config QEMU
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    # Step 3: Config Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Step 4: Login Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }} 
        password: ${{ secrets.DOCKERHUB_TOKEN }}   

    # Step 5: Build và Push image
    - name: Build and push Moodle image
      uses: docker/build-push-action@v5
      with:
        context: . # Build từ dir root
        file: ./Dockerfile # Dockerfile
        push: true # push image lên
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/moodle-lms:latest # Dùng tên repo Docker Hub của bạn